export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";
export const TRANSFER_MOVIE = "TRANSFER_MOVIE";
export const TRANSFER_MOVIE_SUCCESS = "TRANSFER_MOVIE_SUCCESS";
export const TRANSFER_MOVIE_FAILURE = "TRANSFER_MOVIE_FAILURE";
